[platformio]
globallib_dir = ./include/lib

[env:esp32-s3-devkitc-1]
platform = espressif32@ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
lib_ldf_mode = deep+

build_flags = 
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1 
    -DARDUINO_USB_CDC_ON_BOOT=1 
 ;   -I../libraries/merlinIncludes

board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB 
board_build.partitions = min_spiffs.csv

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

upload_speed =  921600
monitor_speed = 115200
monitor_filters =
	default
	esp32_exception_decoder


lib_deps =  
    bblanchon/ArduinoJson @ ^6.20.0
    SPI
    ;https://github.com/Bodmer/TFT_eSPI ; ******* LONG DISPLAY-> don't use '<TFT_eSPI.h>' as it causes issues with the library's configuration file, instead use the full path to the header file in the library folder
    https://github.com/leethomason/tinyxml2
	knolleary/PubSubClient@^2.8
	https://github.com/taranais/NTPClient
	PaulStoffregen/Time
    https://github.com/tzapu/WiFiManager
