#pragma once

const char* SSID = "YOUR_WIFI_SSID";

#define WIFI_ACCESSPOINT "YOUR_PRIMARY_WIFI_SSID"
#define WIFI_ACCESSPOINT_PASSWORD "YOUR_PRIMARY_WIFI_PASSWORD"

#define WIFI_ACCESSPOINT1 "YOUR_SECONDARY_WIFI_SSID"
#define WIFI_ACCESSPOINT_PASSWORD1 "YOUR_SECONDARY_WIFI_PASSWORD"

#define ARDUINO_OTA_URI_SUFFIX "/firmware"

#define OTA_UPDATE_USERNAME "admin"
#define OTA_UPDATE_PASSWORD "CHANGE_ME"


#define MQTT_MAX_PACKET_SIZE 256
#define MQTT_FRIENDLYNAME "mqttDevices"

const char* MQTT_SERVERADDRESS = "192.168.1.55"; //IP address of the MQTT broker
#define MQTT_SERVER_PORT 1883
const char* MQTT_CLIENTNAME = "espTrainMonitor"; //name of the device in MQTT

#define NR_ACCESSTOKEN "YOUR_NATIONAL_RAIL_ACCESS_TOKEN"